server.port=8888
spring.application.name=config-server

spring.cloud.config.server.git.uri=https://github.com/SahanRansika/config-repo
#spring.cloud.config.server.git.uri=https://github.com/SahanRansika/AGMS-Microservices-System/tree/360d75e2a704e81f3b0d6b038266fffa60cc28d3/config-server
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=main
